### ISSUE TITLE
Parse ALL CSS as one line

### ISSUE THREAD

**Issue by KaiTheCEO** [fushra/meml#4]
The only real reason for this is because I feel like it adds a little much when building a website.  It looks weird and users might be a little weirded out. Just an enhancement, not of any real worry.

**Comment by abcdan** [comment]
Minifying?

**Comment by lukasvdberk** [comment]
You mean minify?

**Comment by KaiTheCEO** [comment]
Yeah, I mean minify. Shh, I am very tired

**Comment by abcdan** [comment]
I recommend using this: https://www.npmjs.com/package/minify

**Comment by KaiTheCEO** [comment]
> I recommend using this: https://www.npmjs.com/package/minify

Will implement it when I can! Thank you!

**Comment by trickypr** [comment]
Minifying should only be done in production as it will add considerable time to compiles. The only reason the html from memlc is minified is because it takes more time to create pretty HTML than small HTML.

**Comment by KaiTheCEO** [comment]
I think the best way is to implement a "--production-build" option
