### ISSUE TITLE
Will there be hot reload functionality?

### ISSUE THREAD

**Issue by lukasvdberk** [fushra/meml#6]
For example I edit a .meml file then it will automatically compile and update.

**Comment by abcdan** [comment]
Nodemon support?

**Comment by lukasvdberk** [comment]
Yeah something like that @abcdan

**Comment by KaiTheCEO** [comment]
There are plans for that, yes. No promises that it will be out for A1.0's release

**Comment by trickypr** [comment]
This is now part of `mld`. It will not be coming to memlc.
